language: rust
rust:
  - stable
  - beta
  - nightly

matrix:
  include:
    - rust: nightly
      env: FEATURES=nightly BENCH=true

script:
  - cargo build --verbose --features $FEATURES
  - cargo test --verbose --features $FEATURES
  - '[ "$BENCH" == "true" ] && cargo bench --no-run --verbose --features $FEATURES'
